CREATE DATABASE MOVIES;
USE MOVIES;

CREATE TABLE ACTOR(ACT_ID VARCHAR(20) NOT NULL,
					ACT_NAME VARCHAR(20) NOT NULL,
                    ACT_GENDER VARCHAR(20) NOT NULL);
CREATE TABLE DIRECTOR(DIR_ID VARCHAR(20) NOT NULL,
					DIR_NAME VARCHAR(20) NOT NULL,
                    DIR_PHONE INT(10) NOT NULL);
CREATE TABLE MOVIES(MOV_ID VARCHAR(20) NOT NULL,
					MOV_TITLE VARCHAR(20) NOT NULL,
                    MOV_YEAR VARCHAR(20) NOT NULL,
                    MOV_LANG INT(10) NOT NULL,
                    DIR_ID VARCHAR(20) NOT NULL);
CREATE TABLE MOVIE_CAST(ACT_ID VARCHAR(20) NOT NULL,
					MOV_ID VARCHAR(20) NOT NULL,
                    ROLE VARCHAR(20) NOT NULL);
INSERT INTO ACTOR(ACT_ID,ACT_NAME,ACT_GENDER )VALUES("1","AA","FEMALE");
INSERT INTO ACTOR(ACT_ID,ACT_NAME,ACT_GENDER )VALUES("2","BB","MALE");
INSERT INTO ACTOR(ACT_ID,ACT_NAME,ACT_GENDER )VALUES("3","CC","FEMALE");

INSERT INTO DIRECTOR(DIR_ID,DIR_NAME,DIR_PHONE )VALUES("4","HITCHCOCK","MALE");
INSERT INTO DIRECTOR(DIR_ID,DIR_NAME,DIR_PHONE )VALUES("5","STEVEN SPIELBERG","MALE");

INSERT INTO MOVIES(MOV_ID,MOV_TITLE,MOV_YEAR,MOV_LANG,DIR_ID)VALUES("6","DD","1999","MAL","4");
INSERT INTO MOVIES(MOV_ID,MOV_TITLE,MOV_YEAR,MOV_LANG,DIR_ID)VALUES("7","EE","1998","MAL","5");
INSERT INTO MOVIES(MOV_ID,MOV_TITLE,MOV_YEAR,MOV_LANG,DIR_ID)VALUES("8","FF","2016","MAL","4");
INSERT INTO MOVIES(MOV_ID,MOV_TITLE,MOV_YEAR,MOV_LANG,DIR_ID)VALUES("9","EE","2017","MAL","5");

INSERT INTO MOVIE_CAST(ACT_ID,MOV_ID,ROLE)VALUES("1","6","ACTOR");
INSERT INTO MOVIE_CAST(ACT_ID,MOV_ID,ROLE)VALUES("2","7","DIRECTOR");
CREATE TABLE RATING(MOV_ID VARCHAR(20) NOT NULL,
                    REV_STARS INT(20) NOT NULL);
INSERT INTO RATING(MOV_ID,REV_STARS)VALUES("7","6");
INSERT INTO RATING(MOV_ID,REV_STARS)VALUES("9","7");
SELECT MOV_TITLE FROM  MOVIES WHERE DIR_ID=4;
SELECT MOV_TITLE 
FROM MOVIES M1 JOIN MOVIE_CAST M 
	ON M1.MOV_TITLE=ACTOR.ACT_ID 
JOIN ACTOR A
	ON M.MOV_ID=M1.MOV_ID;